### ISSUE TITLE
Combability with LethalEscape

### ISSUE THREAD

**Issue by koodikas** [TitaniumTurbine/LethalCompanyMod#1]
**Hey I just wanted to ask how this mod works with LethalEscape (or just overall) when I spawn inside enemies outside with it. And is the mod truly a host mod only or does everyone on the lobby require it?** 

What I've understood LethalEscape uses host's shovel damage to do damage to the clients and runs the AI's on their server. Without that the inside enemies wouldn't work properly (at least what I've read on the subject).
I can try on my server how it works with LethalEscape if I get a confirmation this mod is for the host only 😁 I'd rather not start a public lobby before that :)

**Comment by tom-broadbent** [comment]
The mod is not host only at the moment. I've not tested this with lethal escape but I would expect compatibility issues. If clients don't have my mod then it might actually work properly and allow my mod to function purely server-side, but if they do have it then I think they would probably take double damage, as they would be taking client-side damage from my mod, and then server-side damage from lethal escape.
