### ISSUE TITLE
increases the number of monsters with the number of people in the room

### ISSUE THREAD

**Issue by apeng0907** [TitaniumTurbine/LethalCompanyMod#4]
The mod you created brings a lot of joy to my friends. Because we use more company, sometimes it exceeds 8 people, and the number of players often varies. However, changing the configuration every time is very cumbersome. Therefore, I hope you can add an option to increase the number of monsters according to the number of players. For example, if 2-3 monsters appear within a player, 4 players make 8-12 monsters. Alternatively, you can set three levels of difficulty: 1-4 people, 5-8 people, 9-12 people, each with how many monsters appear. Thank you very much!

**Comment by tom-broadbent** [comment]
I've added some new config options which will be released in version 1.1.0.

Min and max enemy counts (or optionally just the max) will be multiplied by the new scaling factor and the number of players. The formula for this is `count = count * playerCountScaling * numberOfPlayers`

You can also disable scaling by setting the scaling factor to 0.

There's an unrelated bug I want fixing before I release the new version but hopefully it will be released soon
