### ISSUE TITLE
[For recently update] so i pretty sure something u forgot, about config feedback

### ISSUE THREAD

**Issue by CoolLKKPS** [TitaniumTurbine/LethalCompanyMod#6]
will update, hang on

**Comment by CoolLKKPS** [comment]
1. so leave blank will use default value, if im not right, this also will be another feedback
 * change default value, inside value will be "All Enemy, Every Inside", and outside value will be "All Enemy, Every Outside"
2. add value "Vanilla", "Modded", "In Dev", "All Enemy"; "Every Inside", "Every Outside", "All Area":
 * u have to choose at least 2 value in order to use, for example "Vanilla, Every Inside"
 * for me, i will set "Vanilla, Modded, Every Inside", "Vanilla, Modded, Every Outside"
 * if already have Enemy IDs in the value, value of Enemy IDs will skipped

**Comment by CoolLKKPS** [comment]
at least add value "Every Inside", "Every Outside"
and add a config option that list all spawnable enemy

**Comment by CoolLKKPS** [comment]
btw uh, how does SpawnChance work? only trigger spawn when the ship landed?

**Comment by CoolLKKPS** [comment]
@TitaniumTurbine btw uh, how does SpawnChance work? only trigger spawn when the ship landed?

**Comment by CoolLKKPS** [comment]
bc if only trigger spawn when the ship landed, that's really not good enough, previously i use MoreMonster and i can able to set how many time passed to spawn a monster inside and/or outside, without that feature the difficulty will rise too fast

**Comment by tom-broadbent** [comment]
> add a config option that list all spawnable enemy

As is explained in the config, all enemy IDs are printed to the BepInEx console when you load into a level. Maybe in the future I will add some presets, but I think for now it is sufficient for users to manually create their own.


> @TitaniumTurbine btw uh, how does SpawnChance work? only trigger spawn when the ship landed?

SpawnChance is the probability of having the enemies spawn. Yes, enemies both inside and outside from the mod will spawn as soon as the ship lands. I may look into creating a way for enemies to spawn over time.
